function [fig_h,axes_h,axes_cb_h]= ...
  figure_position_estimate_snippetized(date_str,letter_str,i_segment, ...
                                       r_est,Covariance_matrix,r_est_all_snippets,is_outlier, ...
                                       r_head_from_video,r_tail_from_video, ...
                                       R,r_corners,x_grid,y_grid)

is_keeper=~is_outlier;
r_est_all_keepers=r_est_all_snippets(:,is_keeper);
r_est_all_outliers=r_est_all_snippets(:,is_outlier);
n_keepers=sum(is_keeper);
n_outliers=sum(is_outlier);

% calculate the pdf at all grid points, so we can show it on the next
% figure
is_valid_estimate=~any(isnan(r_est))&&~any(isnan(Covariance_matrix(:)));
if is_valid_estimate, 
  x_grid_serial=x_grid(:);
  y_grid_serial=y_grid(:);
  r_grid_serial=[x_grid_serial';y_grid_serial'];
  %n_grid_pts=size(r_grid_serial,2);
  pdf_grid_serial=mvnpdf(r_grid_serial',r_est',Covariance_matrix);  % density, units: 1/(m^2)
  pdf_grid=reshape(pdf_grid_serial,size(x_grid));
  pdf_grid_max=max(max(pdf_grid));
else
  pdf_grid=zeros(size(x_grid));
  pdf_grid_max=1;
end

%
% make a figure of the pdf funtion, and the position estimates
%
title_str=sprintf('%s %s seg %d', ...
                  date_str,letter_str,i_segment);
colorbar_label_str='Probability density (1/m^2)';         
clr_anno=[0 0 0];
clr_mouse=[0 0 145]/255;  % m1 color: dark blue
% clr_mice_fake=0.8*[   0  255  255 ; ...
%                    255   69    0 ; ...
%                    255  215    0 ]/255;
do_draw_mic_labels=true;                 

% w_fig=4.5; % in
% h_fig=3; % in
% w_axes=1.8;  % in
% h_axes=1.8;  % in
% w_colorbar=0.1;  % in
% w_colorbar_spacer=0.05;  % in

fig_h=figure('color','w');
%set_figure_size_explicit(fig_h,[w_fig h_fig]);
%axes_h=axes('parent',fig_h,'box','on','ydir','reverse');
axes_h=axes('parent',fig_h,'box','on');
%set(axes_h,'fontsize',7);
%set_axes_size_fixed_center_explicit(axes_h,[w_axes h_axes])

n_mics=size(R,2);
place_objective_map_in_axes(axes_h, ...
                            x_grid,y_grid,pdf_grid, ...
                            @(n)(flipud(0.7+0.3*gray(n))), ...
                            [0 pdf_grid_max], ...
                            title_str, ...
                            zeros(n_mics,3), ...
                            clr_anno, ...
                            r_est,[], ...
                            R,[],[], ...
                            do_draw_mic_labels);
z_mice=1;                          
draw_mice_given_head_and_tail(axes_h,100*r_head_from_video,100*r_tail_from_video,z_mice,clr_mouse);
%draw_mice_given_head_and_tail(axes_h,100*r_head_from_video_fake,100*r_tail_from_video_fake,z_mice,clr_mice_fake);
line('parent',axes_h, ...
     'xdata',100*r_est_all_keepers(1,:), ...
     'ydata',100*r_est_all_keepers(2,:), ...
     'zdata',ones(1,n_keepers), ...
     'marker','+', ...
     'linestyle','none', ...
     'color','k');
line('parent',axes_h, ...
     'xdata',100*r_est(1,:), ...
     'ydata',100*r_est(2,:), ...
     'zdata',1, ...
     'marker','.', ...
     'markersize',6*3, ...
     'linestyle','none', ...
     'color','k');
line('parent',axes_h, ...
     'xdata',100*r_est_all_outliers(1,:), ...
     'ydata',100*r_est_all_outliers(2,:), ...
     'zdata',ones(1,n_outliers), ...
     'marker','o', ...
     'markersize',3, ...
     'linestyle','none', ...
     'color','k');
line('parent',axes_h, ...
     'xdata',100*[r_corners(1,:) r_corners(1,1)], ...
     'ydata',100*[r_corners(2,:) r_corners(2,1)], ...
     'zdata',ones(1,5), ...
     'color','k');
%hold on;
%h_error_ellipse=error_ellipse('mu',100*r_est,'C',100^2*Covariance_matrix,'conf',0.95);
%hold off;
%set(h_error_ellipse,'color','k');
%title(axes_h,title_str,'interpreter','none','fontsize',7);
h=xlabel(axes_h,'x (cm)');
%delete(h);
h=ylabel(axes_h,'y (cm)');  
%delete(h);
%set(axes_h,'ytick',[]);
%set(axes_h,'xtick',[40 60]);

%axes_cb_h=add_colorbar(axes_h,w_colorbar,w_colorbar_spacer);
axes_cb_h=add_colorbar(axes_h);
%set(axes_cb_h,'fontsize',7);
ylabel(axes_cb_h,colorbar_label_str);

end
