function map_multiple_trials_executable(output_file_name,input_file_name)

% make sure the common blob_from_voc_indicators_and_ancillary functions get
% included in the executable:
%#function r_est_from_tf_rect_indicators_and_ancillary

load(input_file_name);
% [r_est,dssen_head]= ...
%   dssen_head_from_file_indicators(base_dir_name,date_str,letter_str, ...
%                                   R,Temp, ...
%                                   dx,x_grid,y_grid,in_cage, ...
%                                   i_syl,i_start,i_end, ...
%                                   f_lo,f_hi, ...
%                                   r_head,r_tail);  %#ok
blob_this_voc = ...
  feval(blob_from_voc_indicators_and_ancillary, ...
        base_dir_name,date_str_this_trial,letter_str_this_trial, ...
        args, ...
        verbosity);  %#ok
% save(output_file_name,'r_est','dssen_head');                                
save(output_file_name,'blob_this_voc');

end
