function place_gridded_function_in_axes(axes_h, ...
                                        x_grid,y_grid,f_grid, ...
                                        color_function, ...
                                        color_limits)


fig_h=get(axes_h,'parent');
colormap(fig_h,feval(color_function,256));

if ~isempty(color_limits)
  set(axes_h,'clim',color_limits);
end

xd=[x_grid(1,1) x_grid(end,1)];
yd=[y_grid(1,1) y_grid(1,end)];
image_handle= ...
  image('parent',axes_h, ...
        'xdata',100*xd, ...
        'ydata',100*yd, ...
        'cdata',f_grid', ...
        'cdatamapping','scaled');  %#ok
    
end
