function [r_est,mse_grid,x_grid,y_grid,i_syl_this, ...
          r_head_this,r_tail_this,R,mse_min,mse_crit, ...
          mse_body,ms_total,a,N,N_filt]= ...
  r_est_random_from_trial_indicators(base_dir_name, ...
                                     data_analysis_dir_name, ...
                                     date_str, ...
                                     letter_str, ...
                                     conf_level, ...
                                     verbosity)

% load the per-trial ancillary data
[i_syl,i_start,i_end,f_lo,f_hi, ...
 r_head,r_tail,R,Temp, ...
 dx,x_grid,y_grid,in_cage]= ...
  ssl_trial_overhead(base_dir_name,data_analysis_dir_name,date_str,letter_str);
n_voc=length(i_syl)

% iterate over the vocalizations in this trial
i_voc=randi(n_voc,1);
i_syl_this=i_syl(i_voc);
i_start_this=i_start(i_voc);
i_end_this=i_end(i_voc);  
f_lo_this=f_lo(i_voc);  
f_hi_this=f_hi(i_voc);  
r_head_this=r_head(:,i_voc);  
r_tail_this=r_tail(:,i_voc);
tic
[r_est,mse_grid,mse_min,mse_crit, ...
 mse_body,ms_total,a,N,N_filt]= ...
  r_est_from_voc_indicators_and_ancillary(base_dir_name, ...
                                          date_str, ...
                                          letter_str, ...
                                          i_syl_this, ...
                                          conf_level, ...
                                          R, Temp, ...
                                          dx,x_grid,y_grid,in_cage, ...
                                          i_start_this,i_end_this,...
                                          f_lo_this,f_hi_this,...
                                          r_head_this,r_tail_this, ...
                                          verbosity);
toc                                

end
