function launchResultsEditor(sJobsDir, ...
                             sResultsDir, ...
                             sTuningDir, ...
                             sClassifiersFile, ...
                             strMovieFileName, ...
                             sTrackFile)

% need a nan as first arg because ResultsEditor() is GUIDE-written
if nargin>=6
  ResultsEditor(nan, ...
                sJobsDir, ...
                sResultsDir, ...
                sTuningDir, ...
                sClassifiersFile, ...
                strMovieFileName, ...
                sTrackFile);
else
  ResultsEditor(nan, ...
                sJobsDir, ...
                sResultsDir, ...
                sTuningDir, ...
                sClassifiersFile, ...
                strMovieFileName);
end
