function fnTrainTdistClassifiersRind(acSMTrackFileNames, ...
                                     strOutputFileName)

% This function loads the single-mouse clip tracks (including HOG vectors),
% computes the identity classifiers, the head-tail classifier, and some
% other stuff, and saves them to an output file.
%
% The name ends in "Rind" because it is called by
% fnTrainTdistClassifiers(), and it calls fnTrainTdistClassifiersCore().

% Load all the SM clip track files                                  
[acBackground,...
 acHOGFeatures, ...
 acHOGFeaturesFlipped, ...
 acPatches, ...
 acX, ...
 acY, ...
 acA, ...
 acB, ...
 acTheta]= ...
  fnLoadSMClipTracks(acSMTrackFileNames);  %#ok

% Train the identity classifiers, train the head-tail classifier,
% extract the appearance features, and extract representative image
% patches for each mouse.
[strctIdentityClassifier, ...
 strctHeadTailClassifier, ...
 strctHeadTailClassifierNeg, ...
 a2fAppearanceFeatures, ...
 a3iRepresentativePatch] = ...
  fnTrainTdistClassifiersCore(acHOGFeatures, ...
                              acHOGFeaturesFlipped, ...
                              acPatches, ...
                              acA, ...
                              acB);  %#ok

% We stuff the representative patches in with the identity classifiers,
% for reasons unclear to me.  (ALT)
% This is also stored as a double array on disk, even though the pel
% values are integers on [0,255].  (ALT)
strctIdentityClassifier.m_a3fRepImages = double(a3iRepresentativePatch);

% save the classifiers and associated data to a .mat file
acMovies=acSMTrackFileNames;  %#ok
save(strOutputFileName,...
     'strctIdentityClassifier', ...
     'strctHeadTailClassifierNeg', ...
     'strctHeadTailClassifier', ...
     'a2fAppearanceFeatures', ...
     'acMovies');

end
