function [strctIdentityClassifier, ...
          strctHeadTailClassifier, ...
          strctHeadTailClassifierNeg, ...          
          a2fAppearanceFeatures, ...
          a3iRepresentativePatch] = ...
  fnTrainTdistClassifiersCore(acHOGFeatures, ...
                              acHOGFeaturesFlipped, ...
                              acPatches, ...
                              acA, ...
                              acB)

% Train the identity classifier for each mouse
fprintf('Training the identity classifer for each mouse...\n');
[strctIdentityClassifier,acHOGFeaturesCulledForID]= ...
  fnCullExemplarsAndTrainTdistIdentityClassifiers(acHOGFeatures, ...
                                                  acA, ...
                                                  acB);
fprintf('Done training the identity classifer for each mouse.\n');
                                                
% Train the (single) head-tail classifier
fprintf('Training the (single) head-tail classifer for all mice...\n');
[strctHeadTailClassifier,strctHeadTailClassifierNeg] = ...
  fnCullExemplarsAndTrainTdistHeadTailClassifier(acHOGFeatures, ...
                                                 acHOGFeaturesFlipped, ...
                                                 acA, ...
                                                 acB);                            
fprintf('Done training the (single) head-tail classifer for all mice.\n');
                            
% Collect a set of appearance HOG vectors from random mice exemplars.
fprintf('Collecting appearance vectors for all mice...\n');
a2fAppearanceFeatures= ...
  fnCollectAppearanceFeatures(acHOGFeaturesCulledForID);
fprintf('Done collecting appearance vectors for all mice.\n');
                            
% Find representative patches for each mouse
fprintf('Finding a representative patch image for each mouse...\n');
a3iRepresentativePatch= ...
  fnFindRepresentativePatches(acPatches, ...
                              acA, ...
                              acB);
fprintf('Done finding a representative patch image for each mouse.\n');

end
