function fnSaveConfigAsXML(strFileName, strctConfig)
%
% Copyright (c) 2008 Shay Ohayon, California Institute of Technology. 
% This file is a part of a free software. you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation (see GPL.txt)
hFileID = fopen(strFileName,'w+');
fprintf(hFileID ,'<?xml version="1.0" encoding="UTF-8"?>\r\n');
fprintf(hFileID ,'<!-- Smart Mouse Configuration -->\r\n\r\n');
fprintf(hFileID ,'<Config>\r\n\r\n');
fprintf(hFileID ,'<Directories\r\n');
fprintf(hFileID , '   DataRootFolder="%s"\r\n',strctConfig.m_strDataRootFolder);
fprintf(hFileID , '   ResultsRootFolder="%s"\r\n',strctConfig.m_strResultsRootFolder);
fprintf(hFileID , '   JobFolder="%s"\r\n',strctConfig.m_strJobFolder);
fprintf(hFileID , '   IdentitiesFolder="%s"\r\n',strctConfig.m_strIdentitiesFolder);
fprintf(hFileID , '> </Directories>\r\n\r\n');

% fprintf(hFileID , '<Configuration\r\n');
% fprintf(hFileID , '    VideoWrapper = "%s"\r\n',strctConfig.m_strVideoWrapper);
% fprintf(hFileID , '> </Configuration>\r\n\r\n');

fprintf(hFileID , '<VideoList>\r\n');
%fprintf(hFileID , '<Name>Generated by GUI</Name>\r\n');
for k=1:length(strctConfig.m_acstrctVideoFiles)
    fprintf(hFileID , '\t<Video file="%s"/>\r\n', ...
        strctConfig.m_acstrctVideoFiles{k}.m_strFileName);
end;
fprintf(hFileID , '</VideoList>\r\n');
fprintf(hFileID , '</Config>\r\n');
fclose(hFileID);

return;
