function [f,Pxx,...
          N_fft, f_res_diam, K, ...
          Pxx_ci, ...
          Pxx_xf, Pxx_xf_sigma, Pxx_xf_ci, ...
          Pxxs_tao]=...
  pow_mt_windowed(dt,x,...
                  NW,K,W_keep,...
                  p_FFT_extra,conf_level,...
                  N_window)
                
% x and should be a col vector

% process args
if nargin<4 || isempty(K)
  K=2*NW-1;
end
if nargin<5 || isempty(W_keep)
  W_keep=fs/2;
end
if nargin<6 || isempty(p_FFT_extra)
  p_FFT_extra=2;
end
if nargin<7 || isempty(conf_level)
  conf_level=0;  % i.e. no confidence intervals
end

% figure the window size
N_raw=size(x,1);
N_per_window=floor(N_raw/N_window);
N_all=N_window*N_per_window;

% trim
x=x(1:N_all);

% divide into windows
x_windowed=reshape(x,[N_per_window N_window]);

% calc the spectrum, averaging over windows
[f,Pxx,...
 N_fft,f_res_diam,K,...
 Pxx_ci,...
 Pxx_xf,Pxx_xf_sigma,Pxx_xf_ci,...
 Pxxs_tao]=...
  pow_mt(dt,x_windowed,...
         NW,K,W_keep,...
         p_FFT_extra,conf_level);
       