function [acstrJobOutFileNames,acstrJobarginFileNames]= ...
  fnCreateJobs(strMovieFileName, ...
               astrctReliableFrames,...
               strAdditionalInfoFileName, ...
               strOutputFolderName, ...
               strJobFolderName)
                             
% Create all the Jobargin<>.mat files for the clip, and put them in
% strJobFolderName.

% Get the clip metadata
strctMovieInfo = fnReadVideoInfo(strMovieFileName);

% Unpack the index of the first and last frames of the clip.
iStartFrame = 1;
iEndFrame = strctMovieInfo.m_iNumFrames;

% Get the number of mice.
iNumMice=length(astrctReliableFrames(1).m_astrctEllipse);

% Make a jobargin file for each interval.
iNumIntervals = length(astrctReliableFrames);
aiReliableFrames = [unique([astrctReliableFrames.m_iFrame]) iEndFrame];
acstrJobOutFileNames=cell(iNumIntervals,1);
acstrJobarginFileNames=cell(iNumIntervals,1);
for iJobIter=1:iNumIntervals
  strctBootstrap.m_astrctEllipse = ...
    astrctReliableFrames(iJobIter).m_astrctEllipse;
  strctBootstrap.m_iNumMice = iNumMice;
  strctBootstrap.m_a2iBackground = ...
    astrctReliableFrames(iJobIter).m_a2iBackground;
  iFirstFrame = astrctReliableFrames(iJobIter).m_iFrame;
  iLastFrame=...
    aiReliableFrames(find(aiReliableFrames==iFirstFrame)+1); % OA - was -1
  aiInterval = iFirstFrame:iLastFrame;
  strJobOutFileName = ...
    fullfile(strOutputFolderName,['JobOut' num2str(iJobIter) '.mat']);
  strJobarginFileName = ...
    fullfile(strJobFolderName,['Jobargin' num2str(iJobIter) '.mat']);
  fnCreateJob(strMovieFileName, ...
              strctMovieInfo, ...
              aiInterval, ...
              strctBootstrap, ...
              strAdditionalInfoFileName, ...
              strJobOutFileName, ...
              iJobIter, ...
              strJobarginFileName);
  acstrJobOutFileNames{iJobIter}=strJobOutFileName;          
  acstrJobarginFileNames{iJobIter}=strJobarginFileName;          
end

% Add a backward job for initial frames, if the first frame of the clip
% is not reliable for whatever reason.
if astrctReliableFrames(1).m_iFrame ~= iStartFrame
  strctBootstrap.m_astrctEllipse = ...
    astrctReliableFrames(1).m_astrctEllipse;
  strctBootstrap.m_iNumMice = iNumMice;
  iJobIter = iNumIntervals+1;  % used to not have +1, ALT 2012-01-10
  aiInterval = astrctReliableFrames(1).m_iFrame:-1:iStartFrame;
  strJobOutFileName = ...
    fullfile(strOutputFolderName,['JobOut' num2str(iJobIter) '.mat']);
  strJobarginFileName = ...
    fullfile(strJobFolderName,['Jobargin' num2str(iJobIter) '.mat']);
  fnCreateJob(strMovieFileName, ...
              strctMovieInfo, ...
              aiInterval, ...
              strctBootstrap, ...
              strAdditionalInfoFileName, ...
              strJobOutFileName, ...
              iJobIter, ...
              strJobarginFileName);
  acstrJobOutFileNames={acstrJobOutFileNames;strJobOutFileName};
  acstrJobarginFileNames={acstrJobarginFileNames;strJobarginFileName};
end

end