function fnSubmitJobToCluster(strJobInputFileName, ...
                              strAppRootFolderName)

% Construct the executable file name.
strExecutableFileNameAbs=fullfile(strAppRootFolderName, ...
                                  'Deploy', ...
                                  'MouseTrackProj', ...
                                  'src', ...
                                  'MouseTrackProj');

%                                
% Make a bash script, which will be submitted via qsub
%

% Figure out the name of the bash script.
[strJobFolderName,strInputFileBaseName]=fileparts(strJobInputFileName);  
strSubmitScriptFileNameRel=['submit_' strInputFileBaseName];
strSubmitScriptFileNameAbs = ...
  fullfile(strJobFolderName,strSubmitScriptFileNameRel);

% Write the file.
hSubmitFileID = fopen(strSubmitScriptFileNameAbs,'w');
fprintf(hSubmitFileID,'#!/bin/bash\n');
fprintf(hSubmitFileID, ...
        '%s %s\n', ...
        strExecutableFileNameAbs, ...
        strJobInputFileName);
fclose(hSubmitFileID);
system(['chmod 755 ',strSubmitScriptFileNameAbs]);

% Compose the qsub command.
strCmd = ...
  sprintf('qsub -N %s -e %s -o %s -b y -cwd -V ''%s''', ...
          strSubmitScriptFileNameRel, ...
          strJobFolderName, ...
          strJobFolderName, ...
          strSubmitScriptFileNameAbs);  

% Show the user the qsub command we're about to invoke.
fprintf('%s\n',strCmd);

% Invoke the qsub command.
system(strCmd);

end
