  function layout(self)
    
    self.fig = figure(...
      'Units','characters',...
      'CloseRequestFcn',@(hObject,eventdata)self.quit(),...
      'Color', get(0,'DefaultUicontrolBackgroundColor'), ...
      'MenuBar','none',...
      'Colormap',gray(256),...
      'IntegerHandle','off',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Name','Catalytic',...
      'NumberTitle','off',...
      'PaperPosition',get(0,'defaultfigurePaperPosition'),...
      'Position',[55 39.9230769230769 184.833333333333 58],...
      'ResizeFcn',@(hObject,eventdata)self.resize(hObject,eventdata),...
      'ToolBar','none',...
      'HandleVisibility','callback',...
      'Tag','fig',...
      'Visible','off');
    %'Color',[0.701960784313725 0.701960784313725 0.701960784313725],...
%      'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
%      'WindowButtonMotionFcn',@(hObject,eventdata)self.mouseMoved(hObject,eventdata),...
%      'WindowButtonUpFcn',@(hObject,eventdata)self.mouseButtonReleased(hObject,eventdata),...
    
    centerOnRoot(self.fig);    
    
    self.mainAxes=axes(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Position',[1.6 16.5 98.4 40.5],...
      'Box','on',...
      'FontName','helvetica',...
      'FontSize',12.5,...
      'Layer','top',...
      'ydir','reverse', ...
      'xtick',[],...
      'ytick',[],...      
      'dataaspectratio',[1 1 1], ...
      'Tag','mainAxes');
%       'LooseInset',[19.8466666666667 5.72 14.5033333333333 3.9],...
%       'CameraPosition',[0.5 0.5 9.16025403784439],...
%       'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
%       'ZColor',get(0,'defaultaxesZColor'),...
%      'XColor',get(0,'defaultaxesXColor'),...
%      'YColor',get(0,'defaultaxesYColor'),...
%      'XTick',[],...
%      'YTick',[],...
%       'XTickMode','manual',...
%       'YTickMode','manual',...
%       'Color',get(0,'defaultaxesColor'),...
%       'ColorOrder',get(0,'defaultaxesColorOrder'),...
%      'ButtonDownFcn',@(hObject,eventdata)self.mainaxes_ButtonDownFcn(hObject,eventdata),...
        
    self.connectpanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Connect Tracks...',...
      'Clipping','on',...
      'Position',[101.6 1.30769230769231 78.4 25.8461538461538],...
      'Visible','off',...
      'Tag','connectpanel'...
      );
    
    self.connectdoitbutton=uicontrol(...
      'Parent',self.connectpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.561 0],...
      'Callback',@(hObject,eventdata)self.connectdoitbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[30.6 1.3076923076923 19.2 2.53846153846154],...
      'String','Do It',...
      'UserData',[],...
      'Tag','connectdoitbutton'...
      );
    
    self.connectcancelbutton=uicontrol(...
      'Parent',self.connectpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.524 0 0],...
      'Callback',@(hObject,eventdata)self.connectcancelbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[51.2 1.23076923076922 18.6 2.53846153846154],...
      'String','Cancel',...
      'UserData',[],...
      'Tag','connectcancelbutton'...
      );
    
    uicontrol(...
      'Parent',self.connectpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','times',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 4.23076923076922 72.4 19.7692307692308],...
      'String',{  'fix errors in which a fly is lost for some'; 'frames: connect the tracks.'; '1) Scroll to the first frame of the portion of'; 'track to be connected. '; '2) Click on the track to be connected.. '; '3) Push "First Fly" button. '; '4) Scroll to the last frame of the portion of'; 'track to be connected. '; '5) Click on the track to be connected. '; '6) Push "Do It" button. ' },...
      'Style','text',...
      'Tag','text28'...
      );
    
    self.connectfirstflybutton=uicontrol(...
      'Parent',self.connectpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.512 0.476 0],...
      'Callback',@(hObject,eventdata)self.connectfirstflybuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[5.8 1.3076923076923 24 2.53846153846154],...
      'String','First Fly',...
      'UserData',[],...
      'Tag','connectfirstflybutton'...
      );
    
    self.frameslider=uicontrol(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.9 0.9 0.9],...
      'Callback',@(hObject,eventdata)self.framesliderTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',12.5,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Max',10000,...
      'Min',1,...
      'Position',[1.6 13.2307692307692 98.4 1.15384615384615],...
      'String',{  'Slider' },...
      'Style','slider',...
      'SliderStep',[1e-05 0.0002],...
      'Value',1,...
      'Tag','frameslider');
    
    self.extendpanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Extend Track...',...
      'Clipping','on',...
      'Position',[101.6 1.38461538461538 78.4 26],...
      'Visible','off',...
      'Tag','extendpanel');
    
    uicontrol(...
      'Parent',self.extendpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','times',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.6 3.92307692307692 73.2 20.2307692307692],...
      'String',{  'Extend track for a selected fly to a'; 'selected frame.'; '1) Click on the fly to be extended.'; '2) Push "First Fly" button to select.'; '3) Scroll to the frame to be extended to.'; '4) Push "Do It" button. ' },...
      'Style','text',...
      'Tag','text30');
    
    self.extenddoitbutton=uicontrol(...
      'Parent',self.extendpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.561 0],...
      'Callback',@(hObject,eventdata)self.extenddoitbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[34.4 0.846153846153846 15.6 2.53846153846154],...
      'String','Do It',...
      'UserData',[],...
      'Tag','extenddoitbutton');
    
    self.extendcancelbutton=uicontrol(...
      'Parent',self.extendpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.524 0 0],...
      'Callback',@(hObject,eventdata)self.extendcancelbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[50.6 0.846153846153846 20.2 2.53846153846154],...
      'String','Cancel',...
      'UserData',[],...
      'Tag','extendcancelbutton');
    
    self.extendfirstflybutton=uicontrol(...
      'Parent',self.extendpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.512 0.476 0],...
      'Callback',@(hObject,eventdata)self.extendfirstflybuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[6.2 0.846153846153846 26.8 2.53846153846154],...
      'String','First Fly',...
      'UserData',[],...
      'Tag','extendfirstflybutton');
    
    self.autotrackpanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Auto-track...',...
      'Clipping','on',...
      'Position',[101.4 1.30769230769231 78.6 26],...
      'Visible','off',...
      'Tag','autotrackpanel');
    
    uicontrol(...
      'Parent',self.autotrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','times',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.66666666666667 7.84615384615385 74.6666666666667 16.0769230769231],...
      'String',{  'Auto-track fly for a few frames. '; '1) Click on the fly to be tracked in the '; 'frame to be tracked from.'; '2) Push "First Frame" button to select.'; '3) Scroll to the frame to be tracked '; 'until.'; '4) Push "Do It" button. ' },...
      'Style','text',...
      'Tag','text31');
    
    self.autotrackdoitbutton=uicontrol(...
      'Parent',self.autotrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.561 0],...
      'Callback',@(hObject,eventdata)self.autotrackdoitbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[36 0.923076923076923 15.8 2.53846153846154],...
      'String','Do It',...
      'UserData',[],...
      'Tag','autotrackdoitbutton');
    
    self.autotrackcancelbutton=uicontrol(...
      'Parent',self.autotrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.524 0 0],...
      'Callback',@(hObject,eventdata)self.autotrackcancelbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[53.6 0.923076923076923 17.6 2.53846153846154],...
      'String','Cancel',...
      'UserData',[],...
      'Tag','autotrackcancelbutton');
    
    self.autotrackfirstframebutton=uicontrol(...
      'Parent',self.autotrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.512 0.476 0],...
      'Callback',@(hObject,eventdata)self.autotrackfirstframebuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[10.4 0.923076923076923 24 2.53846153846154],...
      'String','First Frame',...
      'UserData',[],...
      'Tag','autotrackfirstframebutton');
    
    self.autotracksettingsbutton=uicontrol(...
      'Parent',self.autotrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0 0.524],...
      'Callback',@(hObject,eventdata)self.autotracksettingsbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[10.4 4 24.8 2.53846153846154],...
      'String','Settings...',...
      'UserData',[],...
      'Tag','autotracksettingsbutton');
    
    self.showtrackingbutton=uicontrol(...
      'Parent',self.autotrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Callback',@(hObject,eventdata)self.showtrackingbuttonTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontSize',12.5,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[38.2 4.23076923076923 30.6 1.76923076923077],...
      'String','Show Tracking',...
      'Style','radiobutton',...
      'Tag','showtrackingbutton');
    
    self.flippanel=uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Flip Orientation...',...
      'Clipping','on',...
      'Position',[101.6 1.07692307692308 78.4 25.9230769230769],...
      'Visible','off',...
      'Tag','flippanel');
    
    uicontrol(...
      'Parent',self.flippanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','times',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.6 3.69230769230769 74.2 20.1538461538462],...
      'String',{  'Flip fly''s orientation in an interval.'; '1) Click on the fly to be flipped in '; 'the first frame to be flipped.'; '2) Push "First Frame" button to select.'; '3) Scroll to the frame to be flipped '; 'until.'; '4) Push "Do It" button. ' },...
      'Style','text',...
      'Tag','text33');
    
    self.flipdoitbutton=uicontrol(...
      'Parent',self.flippanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.561 0],...
      'Callback',@(hObject,eventdata)self.flipdoitbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[35 0.384615384615385 15.6 2.53846153846154],...
      'String','Do It',...
      'UserData',[],...
      'Tag','flipdoitbutton');
    
    self.flipcancelbutton=uicontrol(...
      'Parent',self.flippanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.524 0 0],...
      'Callback',@(hObject,eventdata)self.flipcancelbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[52 0.384615384615385 20.4 2.53846153846154],...
      'String','Cancel',...
      'UserData',[],...
      'Tag','flipcancelbutton');
    
    self.flipfirstframebutton=uicontrol(...
      'Parent',self.flippanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.512 0.476 0],...
      'Callback',@(hObject,eventdata)self.flipfirstframebuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[6 0.384615384615385 27.6 2.53846153846154],...
      'String','First Frame',...
      'UserData',[],...
      'Tag','flipfirstframebutton');
    
    self.debugbutton=uicontrol(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Callback',@(hObject,eventdata)self.debugbuttonTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',12.5,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[27.8333333333333 10.1538461538462 22 1.61538461538462],...
      'String','Debug',...
      'Tag','debugbutton');
    
    self.manytrackpanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Auto-track Multiple...',...
      'Clipping','on',...
      'Position',[102 1.07692307692308 78.6666666666667 26],...
      'Visible','off',...
      'Tag','manytrackpanel');
    
    self.manytrackdoitbutton=uicontrol(...
      'Parent',self.manytrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.561 0],...
      'Callback',@(hObject,eventdata)self.manytrackdoitbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[36 0.923076923076923 15.8 2.53846153846154],...
      'String','Do It',...
      'UserData',[],...
      'Tag','manytrackdoitbutton');
    
    self.manytrackcancelbutton=uicontrol(...
      'Parent',self.manytrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.524 0 0],...
      'Callback',@(hObject,eventdata)self.manytrackcancelbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[53.6 0.923076923076923 17.6 2.53846153846154],...
      'String','Cancel',...
      'UserData',[],...
      'Tag','manytrackcancelbutton');
    
    self.manytrackfirstframebutton=uicontrol(...
      'Parent',self.manytrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.512 0.476 0],...
      'Callback',@(hObject,eventdata)self.manytrackfirstframebuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[10.4 0.923076923076923 24.5 2.53846153846154],...
      'String','First Frame',...
      'UserData',[],...
      'Tag','manytrackfirstframebutton');
    
    self.manytracksettingsbutton=uicontrol(...
      'Parent',self.manytrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0 0.524],...
      'Callback',@(hObject,eventdata)self.manytracksettingsbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[10.4 4 24.5 2.53846153846154],...
      'String','Settings...',...
      'UserData',[],...
      'Tag','manytracksettingsbutton');
    
    self.manytrackshowtrackingbutton=uicontrol(...
      'Parent',self.manytrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Callback',@(hObject,eventdata)self.manytrackshowtrackingbuttonTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontSize',12.5,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[38.2 4.38461538461539 30.6 1.76923076923077],...
      'String','Show Tracking',...
      'Style','radiobutton',...
      'Tag','manytrackshowtrackingbutton');
    
    uicontrol(...
      'Parent',self.manytrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','times',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.66666666666667 7.46153846153846 74.6666666666667 16.3076923076923],...
      'String',{  'Auto-track multiple fly for a few frames. '; '1) Click on the flies to be tracked in the '; 'first frame to be tracked.'; '2) Push "First Frame" button to select.'; '3) Scroll to the last frame to be tracked.'; '4) Push "Do It" button. ' },...
      'Style','text',...
      'Tag','text35');
    
    addnewtrackpanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Add New Track...',...
      'Clipping','on',...
      'Position',[102 1.077 78.6666666666667 26],...
      'Visible','off',...
      'Tag','addnewtrackpanel');
    self.addnewtrackpanel=addnewtrackpanel;
    
    self.addnewtrackdoitbutton=uicontrol(...
      'Parent',addnewtrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.561 0],...
      'Callback',@(hObject,eventdata)self.addnewtrackdoitbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[6.33333333333333 0.923076923076923 19 2.53846153846154],...
      'String','Do It',...
      'UserData',[],...
      'Tag','addnewtrackdoitbutton');
    
    self.addnewtrackcancelbutton=uicontrol(...
      'Parent',addnewtrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.524 0 0],...
      'Callback',@(hObject,eventdata)self.addnewtrackcancelbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[53.6 0.923076923076923 17.6 2.53846153846154],...
      'String','Cancel',...
      'UserData',[],...
      'Tag','addnewtrackcancelbutton');
    
    uicontrol(...
      'Parent',addnewtrackpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','times',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.66666666666667 6.15384615384616 74.6666666666667 17.7692307692308],...
      'String',{  'Add a new fly track.'; '1) Scroll to the first frame to be tracked.'; '4) Push "Do It" button. ' },...
      'Style','text',...
      'Tag','text36');
    
    interpolatepanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Interpolate Track...',...
      'Clipping','on',...
      'Position',[101.6 1.38461538461538 78.4 25.7692307692308],...
      'Visible','off',...
      'Tag','interpolatepanel');
    self.interpolatepanel=interpolatepanel;
    
    uicontrol(...
      'Parent',interpolatepanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','times',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.6 3.92307692307692 73.4 19.8461538461538],...
      'String',{  'Interpolate track for selected fly between'; 'selected frames.'; '1) Scroll to the first frame of the portion of'; 'track to be interpolated. '; '2) Click on the fly to be interpolated.'; '3) Push "First Frame" button to select.'; '4) Scroll to the last frame of the portion of'; 'track to be interpolated.'; '3) Push "Do It" button. ' },...
      'Style','text',...
      'Tag','text26');
    
    self.interpolatedoitbutton=uicontrol(...
      'Parent',interpolatepanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.561 0],...
      'Callback',@(hObject,eventdata)self.interpolatedoitbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[30.4 1 19.8 2.53846153846154],...
      'String','Do It',...
      'UserData',[],...
      'Tag','interpolatedoitbutton');
    
    self.cancelinterpolatebutton=uicontrol(...
      'Parent',interpolatepanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.524 0 0],...
      'Callback',@(hObject,eventdata)self.cancelinterpolatebuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[50.4 1 22 2.53846153846154],...
      'String','Cancel',...
      'UserData',[],...
      'Tag','cancelinterpolatebutton');
    
    self.interpolatefirstframebutton=uicontrol(...
      'Parent',interpolatepanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.512 0.476 0],...
      'Callback',@(hObject,eventdata)self.interpolatefirstframebuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[6.6 1 23.8 2.53846153846154],...
      'String','First Frame',...
      'UserData',[],...
      'Tag','interpolatefirstframebutton');
    
    deletepanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Delete Track...',...
      'Clipping','on',...
      'Position',[101.8 1.46153846153846 78.2 25.6923076923077],...
      'Visible','off',...
      'Tag','deletepanel');
    self.deletepanel=deletepanel;
    
    self.deletedoitbutton=uicontrol(...
      'Parent',deletepanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.561 0],...
      'Callback',@(hObject,eventdata)self.deletedoitbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[24.6 1.07692307692308 16.6 2.53846153846154],...
      'String','Do It',...
      'UserData',[],...
      'Tag','deletedoitbutton');
    
    self.deletecancelbutton=uicontrol(...
      'Parent',deletepanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.524 0 0],...
      'Callback',@(hObject,eventdata)self.deletecancelbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[44.6 0.923076923076923 18.2 2.53846153846154],...
      'String','Cancel',...
      'UserData',[],...
      'Tag','deletecancelbutton');
    
    uicontrol(...
      'Parent',deletepanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','times',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.4 7.15384615384615 66.4 16.1538461538462],...
      'String',{  'Delete the track for selected fly from a'; 'selected frame to the end of its track.'; blanks(0); '1) Scroll to the first frame of the portion of'; 'track to be deleted. '; '2) Click on the fly to be deleted. '; '3) Push "Do It" button. ' },...
      'Style','text',...
      'Tag','text14');
    
    swappanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Swap Identities...',...
      'Clipping','on',...
      'Position',[101.6 1.30769230769231 78.4 25.8461538461538],...
      'Visible','off',...
      'Tag','swappanel');
    self.swappanel=swappanel;
    
    uicontrol(...
      'Parent',swappanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','times',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.4 3.46153846153845 72.8 20.3076923076923],...
      'String',{  'Swap identities for a selected pair of flies between'; 'selected frames.'; '1) Scroll to the first frame of the portion of'; 'tracks to be swapped.'; '2) Select the two flies to be swapped.'; '3) Push "First Frame" button to select.'; '4) Scroll to the last frame of the portion of'; 'track to be swapped.'; '5) Push the "Do It" button. ' },...
      'Style','text',...
      'Tag','text16');
    
    self.swapdoitbutton=uicontrol(...
      'Parent',swappanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.537 0],...
      'Callback',@(hObject,eventdata)self.swapdoitbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[29.3333333333333 0.769230769230761 19.1666666666667 2.53846153846154],...
      'String','Do It',...
      'UserData',[],...
      'Tag','swapdoitbutton');
    
    self.renamecancelbutton=uicontrol(...
      'Parent',swappanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.524 0 0],...
      'Callback',@(hObject,eventdata)self.renamecancelbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[51 0.769230769230761 23 2.53846153846154],...
      'String','Cancel',...
      'UserData',[],...
      'Tag','renamecancelbutton');
    
    self.swapfirstframebutton=uicontrol(...
      'Parent',swappanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.512 0.476 0],...
      'Callback',@(hObject,eventdata)self.swapfirstframebuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[3.16666666666667 0.769230769230761 23.8333333333333 2.53846153846154],...
      'String','First Frame',...
      'UserData',[],...
      'Tag','swapfirstframebutton');
    
    self.playstopbutton=uicontrol(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.537 0],...
      'Callback',@(hObject,eventdata)self.playstopbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[52 9.69230769230769 14.4 2.53846153846154],...
      'String','Play',...
      'UserData',[],...
      'Tag','playstopbutton');
    
    self.zoomInButton=uicontrol(...
      'Parent',self.fig,...
      'FontSize',16, ...
      'FontWeight','bold', ...
      'Style','togglebutton', ...
      'Units','characters',...
      'Callback',@(hObject,eventdata)self.zoomInButtonPressed(),...
      'FontName','helvetica',...
      'Position',[91 10.6 4 2]);
%     backgroundColor=get(self.zoomInButton,'backgroundColor');
%     set(self.zoomInButton, ...
%         'CData', ...
%         rgbImageFromPointerCData(zoomInPointerCData(),backgroundColor));
    set(self.zoomInButton,'String','+');  
    
    self.zoomOutButton=uicontrol(...
      'Parent',self.fig,...
      'FontSize',16, ...
      'FontWeight','bold', ...
      'Style','togglebutton', ...
      'Units','characters',...
      'Callback',@(hObject,eventdata)self.zoomOutButtonPressed(),...
      'FontName','helvetica',...
      'Position',[96 10.6 4 2]);
%     backgroundColor=get(self.zoomOutButton,'backgroundColor');
%     set(self.zoomOutButton, ...
%         'CData', ...
%         rgbImageFromPointerCData(zoomOutPointerCData(),backgroundColor));
    set(self.zoomOutButton,'String','-');  
    
    seqinfopanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Sequence Info',...
      'Clipping','on',...
      'Position',[101.6 48.4615384615385 38.4 9],...
      'Tag','seqinfopanel');
    self.seqinfopanel=seqinfopanel;
    
    self.errnumbertext=uicontrol(...
      'Parent',seqinfopanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 5.8 34.2 1.6],...
      'String','Error:',...
      'Style','text',...
      'Tag','errnumbertext');
    
    self.seqframestext=uicontrol(...
      'Parent',seqinfopanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 4.4 34.4 1.6],...
      'String','Frames:',...
      'Style','text',...
      'Tag','seqframestext');
    
    self.seqfliestext=uicontrol(...
      'Parent',seqinfopanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 3 34.4 1.6],...
      'String','Flies:',...
      'Style','text',...
      'Tag','seqfliestext');
    
    self.seqtypetext=uicontrol(...
      'Parent',seqinfopanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 1.6 34.2 1.6],...
      'String','Type: ',...
      'Style','text',...
      'Tag','seqtypetext');
    
    self.seqsusptext=uicontrol(...
      'Parent',seqinfopanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 0.2 34.2 1.6],...
      'String','Susp: ',...
      'Style','text',...
      'Tag','seqsusptext');
    
    frameinfopanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Frame Info',...
      'Clipping','on',...
      'Position',[142.2 48.4615384615385 37.6 9],...
      'Tag','frameinfopanel');
    self.frameinfopanel=frameinfopanel;
    
    uicontrol(...
      'Parent',frameinfopanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 5.8 19.6 1.6],...
      'String','Frame',...
      'Style','text',...
      'Tag','text1');
    
    self.frameedit=uicontrol(...
      'Parent',frameinfopanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[1 1 1],...
      'Callback',@(hObject,eventdata)self.frameeditTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',14,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[23.6 5.6923076923077 12.6 2.07692307692308],...
      'String',blanks(0),...
      'Style','edit',...
      'Tag','frameedit');
    
    self.suspframetext=uicontrol(...
      'Parent',frameinfopanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 2.76923076923077 33.6 1.6],...
      'String','Susp: ',...
      'Style','text',...
      'Tag','suspframetext');
    
    self.frameofseqtext=uicontrol(...
      'Parent',frameinfopanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 4.32307692307692 22 1.6],...
      'String','Frame of Seq: ',...
      'Style','text',...
      'Tag','frameofseqtext');
    
    uicontrol(...
      'Parent',frameinfopanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 1.29230769230769 34 1.6],...
      'String','Current Fly: ',...
      'Style','text',...
      'Tag','selectedflytext',...
      'Visible','off');
    
    navigationpanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Navigation Tools',...
      'Clipping','on',...
      'Position',[101.6 39.4615384615385 78.4 8.53846153846154],...
      'Tag','navigationpanel');
    self.navigationpanel=navigationpanel;
    
    uicontrol(...
      'Parent',navigationpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 5.15384615384616 23.4 1.61538461538461],...
      'String','Next Error Type:',...
      'Style','text',...
      'Tag','text8');
    
    uicontrol(...
      'Parent',navigationpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[2 3.30769230769231 23.6 1.61538461538461],...
      'String','Sort By:',...
      'Style','text',...
      'Tag','text9');
    
    self.correctbutton=uicontrol(...
      'Parent',navigationpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.561 0],...
      'Callback',@(hObject,eventdata)self.correctbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[19.8333333333333 0.384615384615385 19 2.53846153846154],...
      'String','Finish',...
      'UserData',[],...
      'Tag','correctbutton');
    
    self.backbutton=uicontrol(...
      'Parent',navigationpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.549 0.512 0],...
      'Callback',@(hObject,eventdata)self.backbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[41.6666666666667 0.384615384615385 19 2.53846153846154],...
      'String','Back',...
      'UserData',[],...
      'Tag','backbutton');
    
    self.sortbymenu=uicontrol(...
      'Parent',navigationpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[1 1 1],...
      'Callback',@(hObject,eventdata)self.sortbymenuTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',14,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[25.6 3.38461538461539 49 2],...
      'String',{  'Suspiciousness'; 'Frame Number'; 'Fly' },...
      'Style','popupmenu',...
      'Value',1,...
      'Tag','sortbymenu');
    
    self.nexterrortypemenu=uicontrol(...
      'Parent',navigationpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[1 1 1],...
      'Callback',@(hObject,eventdata)self.nexterrortypemenuTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',14,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[25.6 5.30769230769231 49 2],...
      'String','No more errors',...
      'Style','popupmenu',...
      'Value',1,...
      'Tag','nexterrortypemenu');
    
    editpanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Edit Tools',...
      'Clipping','on',...
      'Position',[101.6 27.7692307692308 78.4 4.07692307692308],...
      'Tag','editpanel');
    self.editpanel=editpanel;
    
    self.undobutton=uicontrol(...
      'Parent',editpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0.512 0.476 0],...
      'Callback',@(hObject,eventdata)self.undobuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[61 0.400000000000001 13.6 2.5],...
      'String','Undo',...
      'UserData',[],...
      'Tag','undobutton');
    
    self.gobutton=uicontrol(...
      'Parent',editpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.573 0],...
      'Callback',@(hObject,eventdata)self.gobuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[46 0.400000000000001 13.8 2.5],...
      'String','Go',...
      'UserData',[],...
      'Tag','gobutton');
    
    self.editPopupMenu=uicontrol(...
      'Parent',editpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[1 1 1],...
      'Callback',@(hObject,eventdata)self.editPopupMenuTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',14,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.8 0.538461538461539 42.6 2],...
      'String',{  'Swap Identities...'; ...
                  'Interpolate...'; ...
                  'Flip Orientation...'; ...
                  'Extend Track...'; ...
                  'Add New Track...'; ...
                  'Delete Track...'; ...
                  'Auto-track...'; ...
                  'Auto-track Multiple...'; ...
                  'Connect Tracks...' },...
      'Style','popupmenu',...
      'Value',1,...
      'Tag','editPopupMenu');
    
    self.printbutton= ...
      uicontrol(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Callback',@(hObject,eventdata)self.printbuttonTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',12.5,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[4 10.1538461538462 22 1.61538461538462],...
      'String','Print Trx',...
      'Tag','printbutton');
    
    seekpanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Seek Tools',...
      'Clipping','on',...
      'Position',[102 32.2307692307693 78 6.76923076923077],...
      'Tag','seekpanel');
    self.seekpanel=seekpanel;
    
    self.previousbutton=uicontrol(...
      'Parent',seekpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0 0.573],...
      'Callback',@(hObject,eventdata)self.previousbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[57.6 2.92307692307693 17.8 2.53846153846154],...
      'String','Prev',...
      'UserData',[],...
      'Tag','previousbutton');
    
    self.nextbutton=uicontrol(...
      'Parent',seekpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[0 0.573 0],...
      'Callback',@(hObject,eventdata)self.nextbuttonTwiddled(hObject,eventdata),...
      'CData',[],...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',16,...
      'FontWeight','bold',...
      'ForegroundColor',[1 1 1],...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[37.6 2.92307692307693 19 2.53846153846154],...
      'String','Next',...
      'UserData',[],...
      'Tag','nextbutton');
    
    uicontrol(...
      'Parent',seekpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[2.66666666666667 0.692307692307693 71 1.46153846153846],...
      'String','Seek to Next/Prev in the current axes',...
      'Style','text',...
      'Tag','seekdirtext');
    
    self.seekmenu=uicontrol(...
      'Parent',seekpanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[1 1 1],...
      'Callback',@(hObject,eventdata)self.seekmenuTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',14,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[1.83333333333333 3.15384615384616 34.3333333333333 2],...
      'String',{  'Birth Nearby'; 'Death Nearby' },...
      'Style','popupmenu',...
      'Value',1,...
      'Tag','seekmenu');
    
    self.flipimage_checkbox=uicontrol(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Callback',@(hObject,eventdata)self.flipimage_checkboxTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',12.5,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[68.6666666666667 10.3076923076923 23 1.30769230769231],...
      'String','Flip image',...
      'Style','checkbox',...
      'Tag','flipimage_checkbox', ...
      'visible','off');
    
    displaypanel = uipanel(...
      'Parent',self.fig,...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontName','helvetica',...
      'FontSize',15,...
      'Title','Display',...
      'Clipping','on',...
      'Position',[2.2 1.38461538461538 97 8.07692307692308],...
      'Tag','displaypanel');
    self.displaypanel=displaypanel;
    
    uicontrol(...
      'Parent',displaypanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[2.4 4 40 1.61538461538461],...
      'String','Which Trajectories to Show:',...
      'Style','text',...
      'Tag','text22');
    
    self.plotpathmenu=uicontrol(...
      'Parent',displaypanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[1 1 1],...
      'Callback',@(hObject,eventdata)self.plotpathmenuTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',14,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[35 4-0.1 20 2],...
      'String',{  'All' ; 'Suspicious' ; 'None' },...
      'Style','popupmenu',...
      'Value',1,...
      'Tag','plotpathmenu');
    
    uicontrol(...
      'Parent',displaypanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[53.4+6.6 4 21 1.61538461538461],...
      'String','Trajectory Length:',...
      'Style','text',...
      'Tag','text23');
    
    self.nframesplotedit=uicontrol(...
      'Parent',displaypanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[1 1 1],...
      'Callback',@(hObject,eventdata)self.nframesploteditTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',14,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[74+6.6 4-0.25 11.8 2.07692307692308],...
      'String','101',...
      'Style','edit',...
      'Tag','nframesplotedit');
    
    uicontrol(...
      'Parent',displaypanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',15,...
      'HorizontalAlignment','left',...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[2.4 1.15384615384615 13.1666666666667 1.61538461538462],...
      'String','Auto-Zoom:',...
      'Style','text',...
      'Tag','autoZoomPopupLabelText');
    
    self.autoZoomPopup=uicontrol(...
      'Parent',displaypanel,...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor',[1 1 1],...
      'Callback',@(hObject,eventdata)self.autoZoomPopupTwiddled(hObject,eventdata),...
      'Enable','off',...
      'FontName','helvetica',...
      'FontSize',14,...
      'KeyPressFcn',@(hObject,eventdata)self.keyPressed(hObject,eventdata),...
      'Position',[17 1 26.8 2],...
      'String',{ 'Suspicious' ; 'Whole Arena' ; 'Off'},...
      'Style','popupmenu',...
      'Value',1,...
      'Tag','autoZoomPopup');
    
    fileMenu = uimenu(...
      'Parent',self.fig,...
      'Callback',@(hObject,eventdata)self.fileMenuTwiddled(hObject,eventdata),...
      'Label','File',...
      'Tag','fileMenu');
    self.fileMenu=fileMenu;
    
    self.fileMenuOpenItem=uimenu(...
      'Parent',fileMenu,...
      'Accelerator','O',...
      'Callback',@(hObject,eventdata)self.fileMenuOpenItemTwiddled(hObject,eventdata),...
      'Label','Open...',...
      'Tag','fileMenuOpenItem');
    
    self.fileMenuCloseItem=uimenu(...
      'Parent',fileMenu,...
      'Callback',@(hObject,eventdata)self.fileMenuCloseItemTwiddled(hObject,eventdata),...
      'Enable','off',...
      'Label','Close',...
      'Tag','fileMenuCloseItem');
    
    self.fileMenuSaveItem=uimenu(...
      'Parent',fileMenu,...
      'Accelerator','S',...
      'Callback',@(hObject,eventdata)self.fileMenuSaveItemTwiddled(hObject,eventdata),...
      'Enable','off',...
      'Label','Save',...
      'Separator','on',...
      'Tag','fileMenuSaveItem');
    
    self.fileMenuSaveAsItem=uimenu(...
      'Parent',fileMenu,...
      'Callback',@(hObject,eventdata)self.fileMenuSaveAsItemTwiddled(hObject,eventdata),...
      'Enable','off',...
      'Label','Save As...',...
      'Tag','fileMenuSaveAsItem');
    
    self.fileMenuQuitItem=uimenu(...
      'Parent',fileMenu,...
      'Accelerator','Q',...
      'Callback',@(hObject,eventdata)self.fileMenuQuitItemTwiddled(hObject,eventdata),...
      'Label','Quit',...
      'Separator','on',...
      'Tag','fileMenuQuitItem');

    self.editMenu = uimenu(...
      'Parent',self.fig,...
      'Label','Edit',...
      'Tag','editMenu');
    
    self.editMenuUndoItem=uimenu(...
      'Parent',self.editMenu,...
      'Accelerator','Z',...
      'Callback',@(hObject,eventdata)self.editMenuUndoItemTwiddled(hObject,eventdata),...
      'Label','Undo',...
      'Tag','editMenuUndoItem');

    adjustColorsIfMac(self.fig);
  end  % method

  
  
