function s=fnLoadAlgorithmsConfigNative()

s=struct('m_strctSingleMouseIdentityTracker',...
             struct('m_fNumImagesForBuffer',50,...
                    'm_fMotionThreshold',50,...
                    'm_fOutsideFloorIntensityLevelThreshold',50,...
                    'm_fTailClippingPixels',4,...
                    'm_fHeadTailHighVelocityPixels',6),...
         'm_strctClassifiers',...
             struct('m_strType','Tdist',...
                    'm_fNumHOGBins',10,...
                    'm_fHOG_Dim',837,...
                    'm_fImagePatchWidth',111,...
                    'm_fImagePatchHeight',51,...
                    'm_fMaxSamplesPerMouseForIdentityTraining',10000,...
                    'm_fMaxSamplesPerMouseForHeadTailTraining',5000,...
                    'm_fGoodTrainingSampleMinA',20,...
                    'm_fGoodTrainingSampleMinB',10,...
                    'm_fCrossValidationFold',4,...
                    'm_fNumApperanceSamplesPerMouse',1000),...
         'm_strctSetupParameters',...
             struct('m_fArenaWidthCM',60,...
                    'm_fArenaHeightCM',60,...
                    'm_afTimeStampX',[1 290],...
                    'm_afTimeStampY',[1 24]),...
         'm_strctJobs',...
             struct('m_fLocalMachineBufferSizeInFrames',200),...
         'm_strctBackgroundSubtraction',...
             struct('m_fMotionThreshold',0.2,...
                    'm_fIntensityThresholdInFloor',0.7,...
                    'm_fMotionThresholdOut',0.2,...
                    'm_fIntensityThresholdOutsideFloor',0.7,...
                    'm_fTailClippingPixels',5),...
         'm_strctTracking',...
             struct('m_fNumMissingFramesToDeclareLostMouse',15,...
                    'm_fPositionalPredictionGainDamping',0.1,...
                    'm_fMaxPredictMajorAxis',63,...
                    'm_fMinPredictMajorAxis',12,...
                    'm_fMinPredictMinorAxis',6,...
                    'm_afAxisBounds',[10 20 20 52],...
                    'm_fSearchSpaceHighVelocity',10,...
                    'm_fSearchSpaceInPixLowVelocity',60,...
                    'm_fSearchSpaceInPixHighVelocity',100,...
                    'm_fRecoverLostMouseReliableComponentSizePixels',500,...
                    'm_fNumExpectationMaximizationInitializations',15,...
                    'm_fNumExpectationMaximizationIterations',20,...
                    'm_fExpectationMaximizationDataSubSamplingFactor',6,...
                    'm_fExpectationMaximizationConvergence',1e-15,...
                    'm_fHypothesisScorePositionWeight',0.15,...
                    'm_fLostMouseBigJumpPixels',70,...
                    'm_fLoseMouseReductionInImageCorrelation',-0.01));

end
