function s=fnLoadAnnotationConfigNative()

s=struct('m_strctDirectories',...
             {struct('m_strBehaviorClassifiersFolder',...
                         {'D:\Data\Janelia Farm\BehaviorClassifiers\'})},...
         'm_acBehaviors',...
             {{struct('m_strName',{'Doing Nothing'},'m_afOperatedOnOtherMice',{0}) ...
               struct('m_strName',{'Running'},'m_afOperatedOnOtherMice',{0}) ...
               struct('m_strName',{'Following'},'m_afOperatedOnOtherMice',{1}) ...
               struct('m_strName',{'Head Sniffing'},'m_afOperatedOnOtherMice',{1}) ...
               struct('m_strName',{'Tail Sniffing'},'m_afOperatedOnOtherMice',{1}) ...
               struct('m_strName',{'Fighting'},'m_afOperatedOnOtherMice',{1}) ...
               struct('m_strName',{'Eating'},'m_afOperatedOnOtherMice',{0}) ...
               struct('m_strName',{'Drinking'},'m_afOperatedOnOtherMice',{0}) ...
               struct('m_strName',{'Sleeping'},'m_afOperatedOnOtherMice',{0}) ...
               struct('m_strName',{'Digging'},'m_afOperatedOnOtherMice',{0}) ...
               struct('m_strName',{'Mating'},'m_afOperatedOnOtherMice',{1})}});
     
end
