function s=fnLoadGlobalThresholdsParamsConfigNative()

s=struct('Features', ...
             {struct('bMouseFrame',{0}, ...
                     'bDistances',{1}, ...
                     'aTimeScales',{1}, ...
                     'bMousePair',{1}, ...
                     'bCoordinates',{0}, ...
                     'iSelfTimeScale',{1}, ...
                     'strctBehaviors', ...
                         {struct('Doing_Nothing', ...
                                     {struct('bElapsedFrames',{false}, ...
                                             'bFrequency',{false}, ...
                                             'iFreqTimeScale',{zeros(0,0)})}, ...
                                 'Running',{struct('bElapsedFrames',{false},'bFrequency',{false},'iFreqTimeScale',{zeros(0,0)})}, ...
                                 'Approaching',{struct('bElapsedFrames',{false},'bFrequency',{false},'iFreqTimeScale',{zeros(0,0)})}, ...
                                 'Following',{struct('bElapsedFrames',{false},'bFrequency',{false},'iFreqTimeScale',{zeros(0,0)})}, ...
                                 'Head_Sniffing',{struct('bElapsedFrames',{false},'bFrequency',{false},'iFreqTimeScale',{zeros(0,0)})}, ...
                                 'Tail_Sniffing',{struct('bElapsedFrames',{false},'bFrequency',{false},'iFreqTimeScale',{zeros(0,0)})}, ...
                                 'Fighting',{struct('bElapsedFrames',{false},'bFrequency',{false},'iFreqTimeScale',{zeros(0,0)})}, ...
                                 'Eating',{struct('bElapsedFrames',{false},'bFrequency',{false},'iFreqTimeScale',{zeros(0,0)})}, ...
                                 'Drinking',{struct('bElapsedFrames',{false},'bFrequency',{false},'iFreqTimeScale',{zeros(0,0)})}, ...
                                 'Sleeping',{struct('bElapsedFrames',{false},'bFrequency',{false},'iFreqTimeScale',{zeros(0,0)})}, ...
                                 'Digging',{struct('bElapsedFrames',{false},'bFrequency',{false},'iFreqTimeScale',{zeros(0,0)})}, ...
                                 'Mating',{struct('bElapsedFrames',{false},'bFrequency',{false},'iFreqTimeScale',{zeros(0,0)})})})}, ...
         'MousePOIs', ...
             {{struct('aPointsNum',{[1 1]}, ...
                      'aNormRadii',{[1 0.6]}, ...
                      'aTheta',{[0 0]}) ...
               struct('aPointsNum',{[1 1]}, ...
                      'aNormRadii',{[1 0.6]}, ...
                      'aTheta',{[3.14159265358979 3.14159265358979]})}}, ...
         'Thresholds',{struct('iMaxDistance',{20}, ...
                              'iMinDistance',{0}, ...
                              'fMinRelativeSpeed',{-7}, ...
                              'fMaxRelativeSpeed',{7}, ...
                              'fMaxMouse2Speed',{10}, ...
                              'fMaxMouse1Speed',{10}, ...
                              'fMinMouse1Speed',{0}, ...
                              'fMinMouse2Speed',{0})}, ...
         'sBehaviorType',{'Mating'}, ...
         'POIs',{{zeros(0,0) zeros(0,0)}});
     
end
