function s=fnLoadRepositoryWindowsDefaultConfigNative()

s=struct('m_acstrVideoFiles',...
             {cell(1,0)}, ...
         'm_strDataRootFolder', ...
             {'D:\Data\Janelia Farm\'}, ...
         'm_strIdentitiesFolder', ...
             {'D:\Data\Janelia Farm\Identities\'}, ...
         'm_strJobFolder', ...
             {'D:\Data\Janelia Farm\Jobs\'}, ...
         'm_strResultsRootFolder', ...
             {'D:\Data\Janelia Farm\Results\'});

end
