function s=fnLoadLogFileOptionConfigNative()

s=struct('format',{'pdf'},...
         'stylesheet',{''},...
         'imageFormat',{'jpg'},...
         'figureSnapMethod',{'getframe'},...
         'useNewFigure',{false},...
         'maxHeight',{zeros(0,0)},...
         'maxWidth',{zeros(0,0)},...
         'showCode',{false},...
         'evalCode',{true},...
         'catchError',{true},...
         'createThumbnail',{false},...
         'maxOutputLines',{10000});
     
end
