function s=fnLoadRepositoryUnixDefaultConfigNative()

s=struct('m_acstrVideoFiles',{cell(1,0)}, ...
         'm_strDataRootFolder',{'/groups/egnor/mousetrack/Movies/'}, ...
         'm_strIdentitiesFolder',{'/groups/egnor/home/ohayons/Data/Identities/'}, ...
         'm_strJobFolder',{'/groups/egnor/mousetrack/Jobs_LDA_Logistic/'}, ...
         'm_strResultsRootFolder',{'/groups/egnor/mousetrack/ResultsLDA_Logistic/'});

end
