function [a2fBackground,...
          a2fHOGFeatures, ...
          a2fHOGFeaturesFlipped, ...
          a3iPatches, ...
          afX, ...
          afY, ...
          afA, ...
          afB, ...
          afTheta]= ...
  fnLoadSMClipTrack(strFileName)

% Reads a single Identities.mat file which contains the output of tracking
% a single mouse in a single mouse clip, and computing the HOG vectors,
% etc, from it
%
% % We assume that the file strFileName was written a la:
% strctIdentity=struct('m_a2fMedian',a2fBackground, ...
%                      'm_a3fHOGFeatures',a2fHOGFeatures, ...
%                      'm_a3fHOGFeaturesFlipped',a2fHOGFeaturesFlipped, ...
%                      'm_a3iPatches',a3iPatches, ...
%                      'm_afX',afX, ...
%                      'm_afY',afY, ...
%                      'm_afA',afA, ...
%                      'm_afB',afB, ...
%                      'm_afTheta',afTheta);
% save(strOutputFile,'strctIdentity','strMovieFileName');

strctFile=load(strFileName);
strctIdentity=strctFile.strctIdentity;
a2fBackground=strctIdentity.m_a2fMedian;
a2fHOGFeatures=strctIdentity.m_a3fHOGFeatures;
a2fHOGFeaturesFlipped=strctIdentity.m_a3fHOGFeaturesFlipped;
a3iPatches=strctIdentity.m_a3iPatches;
afX=strctIdentity.m_afX;
afY=strctIdentity.m_afY;
afA=strctIdentity.m_afA;
afB=strctIdentity.m_afB;
afTheta=strctIdentity.m_afTheta;

end
