function astrctTrackersFixed = fnHouseIdentities(astrctTrackers, ...
                                                 strctMovieInfo, ...
                                                 sClassifiersFile)
%
aiBigJumps = ...
  1 + (find(strctMovieInfo.m_afTimestamp(2:end)- ...
            strctMovieInfo.m_afTimestamp(1:end-1) > ...
            1/strctMovieInfo.m_fFPS * 10));

abLargeTimeGap = zeros(1,length(astrctTrackers(1).m_afX))>0;
abLargeTimeGap(aiBigJumps) = 1;

fSwapPenalty = -200;
strctID = load(sClassifiersFile);
astrctTrackersFixed = ...
  fnCorrectIdentitiesOnTheFly(astrctTrackers, ...
                              strctID.strctIdentityClassifier, ...
                              abLargeTimeGap, ...
                              false, ...
                              fSwapPenalty);

end
