function [dssen_body, ...
          i_syl]= ...
  dssen_body_multiple_trials(base_dir_name, ...
                             date_str, ...
                             letter_str)

% base_dir_name a string
% date_str, letter_str each a cell array of strings

n_trials=length(date_str);
dssen_body=cell(n_trials,1);
i_syl=cell(n_trials,1);
verbosity=0;
for i_trial=1:n_trials
  i_trial
  [dssen_body_this,i_syl_this]= ...
    dssen_body_from_trial_indicators(base_dir_name, ...
                                     date_str{i_trial}, ...
                                     letter_str{i_trial}, ...
                                     verbosity);
  dssen_body{i_trial}=dssen_body_this;
  i_syl{i_trial}=i_syl_this;   
end

end
