function [dssen_body,i_syl_all]= ...
  dssen_body_from_trial_indicators(base_dir_name, ...
                                   date_str, ...
                                   letter_str, ...
                                   verbosity)

if nargin<4 || isempty(verbosity)
  verbosity=0;
end

% do all the stuff we only have to do once per trial
[i_syl_all,i_start_all,i_end_all,f_lo_all,f_hi_all, ...
 r_head_all,r_tail_all,R,Temp, ...
 dx,x_grid,y_grid,in_cage]= ...
  ssl_trial_overhead(base_dir_name,date_str,letter_str);
n_voc=length(i_syl_all)

% iterate over the vocalizations in this trial
dssen_body=zeros(n_voc,1);
for i_voc=1:n_voc
  i_voc
  i_syl_this=i_syl_all(i_voc);
  i_start_this=i_start_all(i_voc);
  i_end_this=i_end_all(i_voc);  
  f_lo_this=f_lo_all(i_voc);  
  f_hi_this=f_hi_all(i_voc);  
  r_head_this=r_head_all(:,i_voc);  
  r_tail_this=r_tail_all(:,i_voc);
  %verbosity=(unifrnd(0,1)<0.005);
  tic
  dssen_body_this= ...
    dssen_body_from_voc_indicators_and_ancillary(base_dir_name,date_str,letter_str, ...
                                    R, Temp, ...
                                    dx,x_grid,y_grid,in_cage, ...
                                    i_syl_this,i_start_this,i_end_this,...
                                    f_lo_this,f_hi_this,...
                                    r_head_this,r_tail_this, ...
                                    verbosity);
  toc                                
  dssen_body(i_voc)=dssen_body_this;                                
end

end
