function [obj_func_fig_h,cr_fig_h]= ...
  r_est_figures_from_voc_indicators(base_dir_name,...
                                         date_str, ...
                                         letter_str, ...
                                         i_syl, ...
                                         verbosity)

% call the function to estimate the position, etc.
[r_est,dssen_grid,x_grid,y_grid,dssen_crit,R,r_head,r_tail]= ...
  r_est_from_voc_indicators(base_dir_name,...
                            date_str, ...
                            letter_str, ...
                            i_syl, ...
                            verbosity);

% extrapolate a mouse ellipse
r_center=(r_head+r_tail)/2;
a_vec=r_head-r_center;  % vector
b=norm(a_vec)/3;  % scalar, and a guess at the half-width of the mouse

% Compute the CR borders from the objective function and critical value
in_cr_grid=(dssen_grid<=dssen_crit);
%r_cr_bounds_ij=bwboundaries(in_cr_grid);
%r_cr_bounds=path_xy_from_path_ij(r_cr_bounds_ij,x_grid,y_grid);

% make a figure of the objective funtion, estimate, and CR
title_str=sprintf('%s %s %03d', ...
                  date_str,letter_str,i_syl);
clr_anno=[0 0 0];
clr_mike=[1 0 0 ; ...
          0 0.7 0 ; ...
          0 0 1 ; ...
          0 0.8 0.8 ];
obj_func_fig_h= ...        
  figure_objective_map(x_grid,y_grid,dssen_grid, ...
                       @jet, ...
                       [], ...
                       title_str, ...
                       '\DeltaSSEN (pure)', ...
                       clr_mike, ...
                       clr_anno, ...
                       r_est,[], ...
                       R,r_head,r_tail);
r_mouse_ellipse=polygon_from_ellipse(r_center,a_vec,b);
line(100*r_mouse_ellipse(1,:),100*r_mouse_ellipse(2,:),'color','k');
% line(100*r_est_in_body(1),100*r_est_in_body(2),0, ...
%      'marker','o','linestyle','none','color','w', ...
%      'markersize',6);

% make a separate figure for the CR
clr_anno=[1 1 1];
cr_fig_h=...
  figure_objective_map(x_grid,y_grid,in_cr_grid, ...
                       @jet, ...
                       [], ...
                       title_str, ...
                       'In CR?', ...
                       clr_mike, ...
                       clr_anno, ...
                       r_est,[], ...
                       R,r_head,r_tail);
r_mouse_ellipse=polygon_from_ellipse(r_center,a_vec,b);
line(100*r_mouse_ellipse(1,:),100*r_mouse_ellipse(2,:),'color','w');

end
