function [r_est, ...
          dssen_body, ...
          date_str_this,letter_str_this,i_syl_this]= ...
  r_est_single_random_voc_from_multiple_trials(base_dir_name, ...
                                               date_str, ...
                                               letter_str, ...
                                               verbosity)

% base_dir_name a string
% date_str, letter_str each a cell array of strings

n_trials=length(date_str);
i_trial=randi(n_trials,1);
date_str_this=date_str{i_trial};
letter_str_this=letter_str{i_trial};
[r_est,dssen_body,i_syl_this]= ...
  r_est_random_voc_from_trial_indicators(base_dir_name, ...
                                         date_str_this, ...
                                         letter_str_this, ...
                                         verbosity);

end
