function [r_est,dssen_body,i_syl_this]= ...
  r_est_random_voc_from_trial_indicators(base_dir_name, ...
                                         date_str, ...
                                         letter_str, ...
                                         verbosity)

if nargin<4 || isempty(verbosity)
  verbosity=0;
end

% do all the stuff we only have to do once per trial
[i_syl_all,i_start_all,i_end_all,f_lo_all,f_hi_all, ...
 r_head_all,r_tail_all,R,Temp, ...
 dx,x_grid,y_grid,in_cage]= ...
  ssl_trial_overhead(base_dir_name,date_str,letter_str);
n_voc=length(i_syl_all);

% do a random voc in this trial
i_voc=randi(n_voc,1);
i_syl_this=i_syl_all(i_voc);
i_start_this=i_start_all(i_voc);
i_end_this=i_end_all(i_voc);
f_lo_this=f_lo_all(i_voc);
f_hi_this=f_hi_all(i_voc);
r_head_this=r_head_all(:,i_voc);
r_tail_this=r_tail_all(:,i_voc);
tic
[r_est,dssen_body]= ...
  r_est_from_voc_indicators_and_ancillary(base_dir_name, ...
                                          date_str, ...
                                          letter_str, ...
                                          i_syl_this, ...
                                          R, Temp, ...
                                          dx,x_grid,y_grid,in_cage, ...
                                          i_start_this,i_end_this,...
                                          f_lo_this,f_hi_this,...
                                          r_head_this,r_tail_this, ...
                                          verbosity);
toc                           

end
