function [date_str_flat, ...
          letter_str_flat, ...
          i_syl_flat, ...
          r_est_flat, ...
          a_flat, ...
          mse_min_flat, ...
          mse_body_flat, ...
          ms_total_flat, ...
          r_head_flat, ...
          r_tail_flat, ...
          N_flat, ...
          N_filt_flat, ...
          mse_crit_flat] = ...
  flatten_trials(date_str, ...
                 letter_str, ...
                 i_syl, ...
                 r_est, ...
                 a, ...
                 mse_min, ...
                 mse_body, ...
                 ms_total, ...
                 r_head, ...
                 r_tail, ...
                 N, ...
                 N_filt, ...
                 mse_crit)

% marshall the values across trials into double arrays (not cell
% arrays)
K=4;  % number of mics
mse_min_flat=zeros(0,1);
mse_body_flat=zeros(0,1);
ms_total_flat=zeros(0,1);
N_flat=zeros(0,1);
N_filt_flat=zeros(0,1);
date_str_flat=cell(0,1);
letter_str_flat=cell(0,1);
i_syl_flat=zeros(0,1);
r_est_flat=zeros(2,0);
a_flat=zeros(0,K);
r_head_flat=zeros(2,0);
r_tail_flat=zeros(2,0);
n_trials=length(date_str);
if exist('mse_crit','var')
  mse_crit_flat=zeros(0,1);
end
for j=1:n_trials
  r_est_flat= ...
    [r_est_flat r_est{j}];  %#ok
  a_flat= ...
    [a_flat;a{j}];  %#ok
  r_head_flat= ...
    [r_head_flat r_head{j}];  %#ok
  r_tail_flat= ...
    [r_tail_flat r_tail{j}];  %#ok
  mse_min_flat= ...
    [mse_min_flat;mse_min{j}];  %#ok
  mse_body_flat= ...
    [mse_body_flat;mse_body{j}];  %#ok
  ms_total_flat= ...
    [ms_total_flat;ms_total{j}];  %#ok
  N_flat=[N_flat;N{j}];  %#ok
  N_filt_flat=[N_filt_flat;N_filt{j}];  %#ok
  n_vocs_this=length(mse_min{j});
  date_str_flat_this=cell(n_vocs_this,1);
  date_str_flat_this(:)=date_str(j);
  date_str_flat= ...
    [date_str_flat;date_str_flat_this];  %#ok
  letter_str_flat_this=cell(n_vocs_this,1);
  letter_str_flat_this(:)=letter_str(j);
  letter_str_flat= ...
    [letter_str_flat;letter_str_flat_this];  %#ok
  i_syl_flat= ...
    [i_syl_flat;i_syl{j}];  %#ok
  if exist('mse_crit','var')
    mse_crit_flat= ...
      [mse_crit_flat;mse_crit{j}];  %#ok
  end
end

end
