function [fig_h,axes_h,axes_cb_h]= ...
  figure_objective_map(x_grid,y_grid,objective_grid, ...
                       color_function, ...
                       cl, ...
                       title_str, ...
                       colorbar_label_str, ...
                       clr_mike, ...
                       clr_anno, ...
                       r_est,r_cr, ...
                       R,r_head,r_tail)

fig_h=figure('color','w');
[axes_h,axes_cb_h] = ...
  axes_objective_map(fig_h, ...
                     x_grid,y_grid,objective_grid, ...
                     color_function, ...
                     cl, ...
                     title_str, ...
                     colorbar_label_str, ...
                     clr_mike, ...
                     clr_anno, ...
                     r_est,r_cr, ...
                     R,r_head,r_tail);
                     
end
