function [date_str_flat, ...
          letter_str_flat, ...
          i_syl_flat, ...
          r_est_flat, ...
          a_flat, ...
          mse_min_flat, ...
          mse_body_flat, ...
          ms_total_flat, ...
          r_head_flat, ...
          r_tail_flat, ...
          N_flat, ...
          N_filt_flat, ...
          mse_crit_flat] = ...
  flatten_trials(r_est_blob_per_voc_per_trial, ...
                 per_trial_ancillary)

% marshall the values across trials into double arrays (not cell
% arrays)
K=4;  % number of mics
mse_min_flat=zeros(0,1);
mse_body_flat=zeros(0,1);
ms_total_flat=zeros(0,1);
N_flat=zeros(0,1);
N_filt_flat=zeros(0,1);
date_str_flat=cell(0,1);
letter_str_flat=cell(0,1);
i_syl_flat=zeros(0,1);
r_est_flat=zeros(2,0);
a_flat=zeros(0,K);
r_head_flat=zeros(2,0);
r_tail_flat=zeros(2,0);
n_trials=length(r_est_blob_per_voc_per_trial);
if n_trials>0 && isfield(r_est_blob_per_voc_per_trial{1},'mse_crit')
  mse_crit_flat=zeros(0,1);
end
for j=1:n_trials
  n_vocs_this=length([r_est_blob_per_voc_per_trial{j}.mse_min]);
  r_est_flat= ...
    [r_est_flat r_est_blob_per_voc_per_trial{j}.r_est];  %#ok
  a_flat_this=reshape([r_est_blob_per_voc_per_trial{j}.a],[n_vocs_this K]);
  a_flat= ...
    [a_flat ; ...
     a_flat_this];  %#ok
  r_head_flat= ...
    [r_head_flat r_est_blob_per_voc_per_trial{j}.r_head];  %#ok
  r_tail_flat= ...
    [r_tail_flat r_est_blob_per_voc_per_trial{j}.r_tail];  %#ok
  mse_min_flat= ...
    [mse_min_flat ; ...
     [r_est_blob_per_voc_per_trial{j}.mse_min]' ];  %#ok
  mse_body_flat= ...
    [mse_body_flat ; ...
     [r_est_blob_per_voc_per_trial{j}.mse_body]' ];  %#ok
  ms_total_flat= ...
    [ms_total_flat ; ...
     [r_est_blob_per_voc_per_trial{j}.ms_total]' ];  %#ok
  N_flat=[N_flat ; ...
          [r_est_blob_per_voc_per_trial{j}.N]' ];  %#ok
  N_filt_flat=[N_filt_flat ; ...
               [r_est_blob_per_voc_per_trial{j}.N_filt]' ];  %#ok
  n_vocs_this=length([r_est_blob_per_voc_per_trial{j}.mse_min]);
  date_str_flat_this= ...
    repmat({per_trial_ancillary(j).date_str},[n_vocs_this 1]);
  date_str_flat= ...
    [date_str_flat ; ...
     date_str_flat_this];  %#ok
  letter_str_flat_this= ...
    repmat({per_trial_ancillary(j).letter_str},[n_vocs_this 1]);
  letter_str_flat= ...
    [letter_str_flat ; ...
     letter_str_flat_this];  %#ok
  i_syl_flat= ...
    [i_syl_flat ; ...
     [r_est_blob_per_voc_per_trial{j}.i_syl]' ];  %#ok
  if exist('mse_crit_flat','var')
    mse_crit_flat= ...
      [mse_crit_flat ; ...
       [r_est_blob_per_voc_per_trial{j}.mse_crit]' ];  %#ok
  end
end

end
