function [r_est,i_syl,r_head,r_tail,R,mse_min,mse_crit, ...
          mse_body,P_body,ms_total,a,N,N_filt]= ...
  r_est_from_trial_indicators(base_dir_name, ...
                              date_str, ...
                              letter_str, ...
                              conf_level, ...
                              verbosity)

% load the per-trial ancillary data
[i_syl,i_start,i_end,f_lo,f_hi, ...
 r_head,r_tail,R,Temp, ...
 dx,x_grid,y_grid,in_cage]= ...
  ssl_trial_overhead(base_dir_name,date_str,letter_str);
n_voc=length(i_syl);
n_mice=size(r_head,3);

% iterate over the vocalizations in this trial
[~,K]=size(R);
r_est=zeros(2,n_voc);
mse_min=zeros(n_voc,1);
mse_crit=zeros(n_voc,1);
mse_body=zeros(n_voc,n_mice);
P_body=zeros(n_voc,n_mice);
ms_total=zeros(n_voc,1);
a=zeros(n_voc,K);
N=zeros(n_voc,1);
N_filt=zeros(n_voc,1);
for i_voc=1:250
  i_voc
  i_syl_this=i_syl(i_voc);
  i_start_this=i_start(i_voc);
  i_end_this=i_end(i_voc);  
  f_lo_this=f_lo(i_voc);  
  f_hi_this=f_hi(i_voc);  
  r_head_this=reshape(r_head(:,i_voc,:),[2 n_mice]);  
  r_tail_this=reshape(r_tail(:,i_voc,:),[2 n_mice]);
  tic
  [r_est_this,~,mse_min_this,mse_crit_this, ...
   mse_body_this,P_body_this,ms_total_this,a_this,N_this,N_filt_this]= ...
    r_est_from_tf_rect_indicators_and_ancillary(base_dir_name, ...
                                                date_str, ...
                                                letter_str, ...
                                                i_syl_this, ...
                                                conf_level, ...
                                                R, Temp, ...
                                                dx,x_grid,y_grid,in_cage, ...
                                                i_start_this,i_end_this,...
                                                f_lo_this,f_hi_this,...
                                                r_head_this,r_tail_this, ...
                                                verbosity);
  toc                                
  r_est(:,i_voc)=r_est_this;
  mse_min(i_voc)=mse_min_this;
  mse_crit(i_voc)=mse_crit_this;
  mse_body(i_voc,:)=mse_body_this;
  P_body(i_voc,:)=P_body_this;
  ms_total(i_voc)=ms_total_this;
  a(i_voc,:)=a_this;
  N(i_voc)=N_this;
  N_filt(i_voc)=N_filt_this;
end

end
