function [r_est, ...
          i_syl, ...
          r_head,r_tail, ...
          R, ...
          mse_min, ...
          mse_crit, ...
          mse_body, ...
          P_body, ...
          ms_total, ...
          a, ...
          N, ...
          N_filt]= ...
  r_est_multiple_trials(base_dir_name, ...
                        date_str, ...
                        letter_str, ...
                        conf_level, ...
                        verbosity)

% base_dir_name a string
% date_str, letter_str each a cell array of strings

n_trials=length(date_str);
r_est=cell(n_trials,1);
i_syl=cell(n_trials,1);
r_head=cell(n_trials,1);
r_tail=cell(n_trials,1);
n_mics=4;
R=zeros(3,n_mics,n_trials);
mse_min=cell(n_trials,1);
mse_crit=cell(n_trials,1);
mse_body=cell(n_trials,1);
P_body=cell(n_trials,1);
ms_total=cell(n_trials,1);
a=cell(n_trials,1);
N=cell(n_trials,1);
N_filt=cell(n_trials,1);
for i_trial=1:n_trials
  i_trial
  [r_est_this,i_syl_this,r_head_this,r_tail_this,R_this, ...
   mse_min_this,mse_crit_this,mse_body_this,P_body_this,ms_total_this, ...
   a_this,N_this,N_filt_this]= ...
    r_est_from_trial_indicators(base_dir_name, ...
                                date_str{i_trial}, ...
                                letter_str{i_trial}, ...
                                conf_level, ...
                                verbosity);
  r_est{i_trial}=r_est_this;                            
  i_syl{i_trial}=i_syl_this;   
  r_head{i_trial}=r_head_this;   
  r_tail{i_trial}=r_tail_this;   
  R(:,:,i_trial)=R_this;
  mse_min{i_trial}=mse_min_this;   
  mse_crit{i_trial}=mse_crit_this;   
  mse_body{i_trial}=mse_body_this;   
  P_body{i_trial}=P_body_this;   
  ms_total{i_trial}=ms_total_this;   
  a{i_trial}=a_this;
  N{i_trial}=N_this;   
  N_filt{i_trial}=N_filt_this;   
end

end
